[package]
name = "rod"
version = "0.2.0"
edition = "2024"

[dependencies]
regex = { version = "1.11.2", optional = true }
rod_derive = { path = "./rod_derive", version = "0.2.0" }

[features]
default = ["regex"]
regex = ["dep:regex", "rod_derive/regex"]


